import type { ClaimedIdea, WorkflowGuide, WorkflowTemplate } from "@/lib/execution";

export const WORKFLOW_GUIDES: WorkflowGuide[] = [
  {
    slug: "claim-to-launch",
    title: "Claim-to-Launch Guide",
    summary: "How to move from a claimed idea to weekly execution without waiting for full automation.",
    body: "Start from one claimed opportunity, pick one workflow that gets you closer to revenue, and force every agent output into a weekly operating cadence. Validate the pattern manually first, then add automation only after the founder repeats the workflow at least twice.",
  },
  {
    slug: "source-of-truth",
    title: "Source of Truth Setup",
    summary: "Keep the team aligned on one brief, one CRM, one task queue, and one content repository.",
    body: "Each workflow should read from a shared brief, write to a single operating sheet or CRM, and publish assets into a searchable library. The MVP rule is simple: the workflow can touch many tools, but it must have exactly one system of record for decisions and one for work in progress.",
  },
  {
    slug: "agent-handoffs",
    title: "Agent Handoff Rules",
    summary: "Productize the handoff, not just the prompt, so agents behave like a team.",
    body: "Every workflow should declare which agent starts it, what artifact gets handed off, and which metric proves completion. Keep prompts thin and outputs structured so GTM, Sales, Marketing, and Engineering can operate on the same payload without reinterpreting the whole task from scratch.",
  },
];

export const WORKFLOW_LIBRARY: WorkflowTemplate[] = [
  {
    slug: "competitive-landscape-brief",
    title: "Competitive landscape brief",
    one_liner: "Map direct, adjacent, and substitute competitors with positioning notes — before GTM writes a single message.",
    category: "Research",
    stage: "Foundation",
    primary_agent: "research",
    support_agents: ["gtm", "marketing"],
    setup_time: "Half day",
    automation_level: "Agent-assisted",
    objective: "Ground positioning, pricing, and messaging in a real competitor landscape rather than a guess about who's out there.",
    when_to_use: "Run this immediately after the idea is claimed, before the GTM agent locks the wedge. Re-run any time a major competitor moves.",
    inputs: ["Claimed idea brief", "Current best guess at the category name", "Any competitor names the founder has heard of"],
    outputs: ["10–15 mapped competitors with positioning", "Adjacent / substitute matrix", "Three pricing benchmarks", "Implied whitespace for the wedge"],
    tool_surfaces: [
      { name: "Industry report search", purpose: "Pull Gartner / IDC / Forrester / Statista views of the segment." },
      { name: "Competitor landscape scan", purpose: "Map vendors with positioning and recent product moves." },
      { name: "Public pricing pages", purpose: "Anchor the offer in real market price points." },
    ],
    steps: [
      { owner: "research", title: "Scope the category", description: "Convert the claimed idea into a specific category description (audience + workflow + scope)." },
      { owner: "research", title: "Run landscape_competitors", description: "Pull 10–15 candidates, dedupe by host, and add one-line positioning to each." },
      { owner: "research", title: "Pull two industry reports", description: "Cite at least two named research firms for sizing or growth claims." },
      { owner: "gtm", title: "Pick the whitespace", description: "Decide which competitor cluster the wedge slots against and which it ignores." },
      { owner: "marketing", title: "Rewrite the promise", description: "Reshape the landing-page headline to occupy the whitespace, not chase a leader." },
    ],
    implementation: {
      validated: "Run as a single shared doc with the founder, before any outbound or landing-page work begins.",
      agentic: "Research agent drives all data collection; GTM and Marketing agents consume the brief and react to it.",
      automation: "Later, watch competitor sites weekly for pricing or product changes and re-issue the brief.",
    },
    metrics: ["Time from claim to landscape brief", "Wedge revision count after the brief lands", "Number of cited sources per claim"],
    tags: ["research", "competitive", "positioning", "foundation"],
    fit: {},
  },
  {
    slug: "ma-radar",
    title: "M&A radar",
    one_liner: "Surface 24 months of acquisitions and consolidation in the sector — and read where the wedge is from who's buying whom.",
    category: "Research",
    stage: "Foundation",
    primary_agent: "research",
    support_agents: ["gtm"],
    setup_time: "Half day",
    automation_level: "Agent-assisted",
    objective: "Identify consolidating acquirers and abandoned segments so the founder enters a market that's opening, not closing.",
    when_to_use: "Run alongside the competitive landscape brief at the foundation stage, and whenever a major incumbent makes a deal.",
    inputs: ["Sector or category name", "Optional list of suspected acquirers"],
    outputs: ["Deals timeline (24 months)", "Acquirer cluster map", "List of segments the consolidators are abandoning", "One \"where the wedge is\" recommendation"],
    tool_surfaces: [
      { name: "Acquisitions and M&A radar", purpose: "Surface recent deals with dates and acquirer names." },
      { name: "Public press releases", purpose: "Verify each deal via primary source." },
      { name: "Founder shared brief", purpose: "Capture the \"who is consolidating\" read for GTM." },
    ],
    steps: [
      { owner: "research", title: "Define the sector", description: "Lock the sector vocabulary so the M&A query stays narrow." },
      { owner: "research", title: "Run find_acquisitions", description: "Pull deals from the last 24 months and cluster by acquirer." },
      { owner: "research", title: "Read the abandonment signal", description: "Flag segments the consolidators have stopped serving — those are wedge candidates." },
      { owner: "gtm", title: "Pick the entry segment", description: "Choose the abandoned segment with the strongest demand evidence and feed it into the wedge plan." },
    ],
    implementation: {
      validated: "Run as a one-time research session before locking the wedge.",
      agentic: "Research agent runs find_acquisitions + fetch_url to verify deals; GTM agent consumes the synthesis.",
      automation: "Later, schedule a monthly M&A digest for the sector and alert the team when an acquirer enters or exits.",
    },
    metrics: ["Number of cited deals in the brief", "Time from radar to wedge decision", "Wedge confidence delta after the brief"],
    tags: ["research", "m&a", "consolidation", "foundation"],
    fit: {},
  },
  {
    slug: "icp-wedge-builder",
    title: "ICP wedge builder",
    one_liner: "Turn a broad startup idea into one buyer, one pain event, and one launch-ready offer.",
    category: "GTM",
    stage: "Foundation",
    primary_agent: "gtm",
    support_agents: ["sales", "marketing"],
    setup_time: "Half day",
    automation_level: "Manual-first",
    objective: "Reduce idea sprawl by forcing the founder to choose a narrow market entry wedge before building too much product.",
    when_to_use: "Use this immediately after an idea is claimed or whenever the team keeps describing multiple buyers and multiple jobs-to-be-done.",
    inputs: ["Claimed idea brief", "3-5 customer or source notes", "Current assumptions about price and buyer"],
    outputs: ["Primary ICP memo", "Pain-event map", "Offer and pricing hypothesis", "Kill criteria for the wedge"],
    tool_surfaces: [
      { name: "Greenfield brief", purpose: "Start from the gap, why-now case, and build path." },
      { name: "Research sources", purpose: "Ground positioning in real category language and timing." },
      { name: "Workspace doc", purpose: "Store the ICP memo and weekly updates." },
    ],
    steps: [
      { owner: "gtm", title: "Distill the wedge", description: "Turn the claimed idea into one buyer segment, one painful workflow, and one trigger that makes the problem urgent." },
      { owner: "sales", title: "Reality-check the buyer", description: "Find five real targets and confirm whether the proposed buyer actually owns the budget or influence." },
      { owner: "marketing", title: "Rewrite the promise", description: "Convert the wedge into a landing-page headline, a one-line value prop, and one proof angle." },
    ],
    implementation: {
      validated: "Run it as a shared doc and one 45-minute working session with the founder.",
      agentic: "Have the GTM agent draft the wedge, the Sales agent pressure-test buyers, and the Marketing agent rewrite the narrative.",
      automation: "Later, pull source excerpts and meeting notes automatically into the shared ICP memo.",
    },
    metrics: ["Time from claim to first ICP memo", "Number of wedge revisions", "Landing-page or reply-rate lift after narrowing"],
    tags: ["b2b", "b2c", "positioning", "early-stage"],
    fit: {},
  },
  {
    slug: "design-partner-recruiter",
    title: "Design partner recruiter",
    one_liner: "Build a short list of design partners and move them into live discovery or pilot calls.",
    category: "Sales",
    stage: "Foundation",
    primary_agent: "sales",
    support_agents: ["gtm"],
    setup_time: "1 day",
    automation_level: "Agent-assisted",
    objective: "Create real customer pull and pressure-test whether the problem is urgent enough to justify founder focus.",
    when_to_use: "Use this when the product is still forming and the founder needs live conversations with target buyers before building deeper.",
    inputs: ["Claimed idea and ICP memo", "Target account criteria", "Founder calendar availability"],
    outputs: ["Prioritized prospect list", "Outreach scripts", "Call agenda", "Pilot tracker"],
    tool_surfaces: [
      { name: "LinkedIn", purpose: "Find likely buyers, operators, or champions." },
      { name: "Lead sheet or CRM", purpose: "Track status and follow-up." },
      { name: "Email inbox", purpose: "Send founder-led outreach and replies." },
    ],
    steps: [
      { owner: "sales", title: "Build the list", description: "Create a tight list of prospects that match the initial wedge and can give strong signal quickly." },
      { owner: "gtm", title: "Tailor the ask", description: "Write outreach that names the problem, the timing shift, and the specific reason this buyer should talk now." },
      { owner: "sales", title: "Run the follow-up loop", description: "Track responses, book calls, and log every objection or edge case." },
    ],
    implementation: {
      validated: "Run it manually in a spreadsheet with one founder-owned sequence.",
      agentic: "Use the Sales agent to draft lists and follow-up copy while GTM tunes the positioning.",
      automation: "Later, pipe lead sources and email status into a single pipeline view.",
    },
    metrics: ["Reply rate", "Calls booked", "Pilot-interest rate", "Top recurring objections"],
    tags: ["b2b", "design-partners", "outbound"],
    fit: { audiences: ["B2B"] },
  },
  {
    slug: "founder-led-outbound-sprint",
    title: "Founder-led outbound sprint",
    one_liner: "Run a weekly outbound motion that turns one message and one buyer into pipeline.",
    category: "Sales",
    stage: "Launch",
    primary_agent: "sales",
    support_agents: ["gtm", "marketing"],
    setup_time: "1 day",
    automation_level: "Agent-assisted",
    objective: "Translate a claimed idea into consistent revenue-generating outreach without pretending the founder already has a sales team.",
    when_to_use: "Use this once the wedge is clear enough to ask for a sale, pilot, or paid discovery conversation.",
    inputs: ["ICP memo", "Offer and pricing hypothesis", "Prospect list", "Existing objections"],
    outputs: ["Weekly outbound batch", "Personalized first-touch scripts", "Objection tracker", "Pipeline review"],
    tool_surfaces: [
      { name: "CRM or Airtable", purpose: "Hold targets, stages, and next steps." },
      { name: "Email or LinkedIn", purpose: "Deliver sequences and founder follow-ups." },
      { name: "Call notes", purpose: "Capture objections and buying triggers." },
    ],
    steps: [
      { owner: "gtm", title: "Lock the thesis", description: "Choose one angle for the week so the founder is not testing five messages at once." },
      { owner: "sales", title: "Ship the batch", description: "Send the weekly sequence, track responses, and push hot prospects into calls fast." },
      { owner: "marketing", title: "Supply proof", description: "Feed the sequence with short proof assets, screenshots, or case snippets that lower skepticism." },
    ],
    implementation: {
      validated: "Use one spreadsheet, one weekly send window, and one review meeting.",
      agentic: "Let Sales assemble the list, GTM rewrite the messaging, and Marketing attach proof assets.",
      automation: "Later, auto-score prospects and sync replies into the pipeline board.",
    },
    metrics: ["Meetings booked", "Pipeline value created", "Positive-reply rate", "Time to first revenue conversation"],
    tags: ["b2b", "revenue", "outbound"],
    fit: { audiences: ["B2B"], founder_paths: ["Bootstrap", "VC-backed"] },
  },
  {
    slug: "pricing-objection-map",
    title: "Pricing objection map",
    one_liner: "Turn confusing pricing conversations into a sharper offer and a cleaner close path.",
    category: "GTM",
    stage: "Revenue",
    primary_agent: "gtm",
    support_agents: ["sales"],
    setup_time: "2 hours",
    automation_level: "Manual-first",
    objective: "Diagnose whether the current pricing problem is really a pricing problem, a packaging problem, or a proof problem.",
    when_to_use: "Use this after 5-10 sales conversations when buyers keep stalling, downscoping, or asking for custom pricing logic.",
    inputs: ["Call notes", "Current pricing page or deck", "Closed-lost reasons", "Pilot requests"],
    outputs: ["Objection taxonomy", "Revised package table", "Proof gaps list", "Next test plan"],
    tool_surfaces: [
      { name: "Call transcripts", purpose: "Source real buyer language and hesitation points." },
      { name: "Pricing sheet", purpose: "Capture current packages, limits, and exceptions." },
      { name: "Shared dashboard", purpose: "Track which experiments improve close quality." },
    ],
    steps: [
      { owner: "sales", title: "Collect the friction", description: "Extract the exact moments where pricing or packaging blocked the deal." },
      { owner: "gtm", title: "Sort the objections", description: "Separate true pricing pressure from missing proof, wrong buyer, or unclear outcomes." },
      { owner: "sales", title: "Retest the package", description: "Use the revised offer in the next batch of conversations and compare outcomes." },
    ],
    implementation: {
      validated: "Review the last ten conversations and score each objection manually.",
      agentic: "Use the GTM agent to classify objections and propose packaging changes from call notes.",
      automation: "Later, pipe call summaries into an objection board with recurring labels.",
    },
    metrics: ["Close rate after pricing changes", "Discount frequency", "Time to proposal acceptance"],
    tags: ["b2b", "pricing", "sales-learnings"],
    fit: { audiences: ["B2B"] },
  },
  {
    slug: "customer-voice-miner",
    title: "Customer voice miner",
    one_liner: "Extract pain language, triggers, and proof phrases from calls, communities, and source links.",
    category: "Marketing",
    stage: "Foundation",
    primary_agent: "marketing",
    support_agents: ["gtm"],
    setup_time: "Half day",
    automation_level: "Agent-assisted",
    objective: "Stop writing generic positioning and instead mirror the language customers already use when describing the pain.",
    when_to_use: "Use this before rewriting the homepage, building outbound scripts, or packaging launch content.",
    inputs: ["Customer calls", "Source citations", "Founder notes", "Community threads"],
    outputs: ["Message bank", "Pain phrases", "Proof snippets", "Headline options"],
    tool_surfaces: [
      { name: "Call notes", purpose: "Capture real operator language." },
      { name: "Community threads", purpose: "See how the market complains in public." },
      { name: "Research sources", purpose: "Ground the story in timing and market context." },
    ],
    steps: [
      { owner: "marketing", title: "Mine the phrases", description: "Collect direct pain language, desired outcomes, and signs that timing matters now." },
      { owner: "gtm", title: "Prioritize the message", description: "Choose the phrases that map to the primary wedge and drop the rest." },
      { owner: "marketing", title: "Publish the stack", description: "Turn the shortlist into homepage copy, launch posts, and response snippets." },
    ],
    implementation: {
      validated: "Run a manual sweep of notes and sources into a single phrase bank.",
      agentic: "Use the Marketing agent to classify pain and the GTM agent to cut it to the top message.",
      automation: "Later, auto-ingest call summaries and source snippets into the same phrase library.",
    },
    metrics: ["Message reuse across surfaces", "Landing-page conversion", "Reply-rate lift after copy changes"],
    tags: ["b2b", "b2c", "messaging", "content"],
    fit: {},
  },
  {
    slug: "launch-asset-repurposer",
    title: "Launch asset repurposer",
    one_liner: "Take one founder insight or customer proof point and explode it into launch-ready assets.",
    category: "Marketing",
    stage: "Launch",
    primary_agent: "marketing",
    support_agents: ["gtm", "sales"],
    setup_time: "2 hours",
    automation_level: "Agent-assisted",
    objective: "Increase output quality and consistency without making the founder write every asset from scratch.",
    when_to_use: "Use this when the team has a strong message or customer story but needs more distribution volume quickly.",
    inputs: ["One long-form source asset", "Current offer", "Target channel list"],
    outputs: ["Landing-page section", "Email copy", "Founder post", "Sales proof snippet", "FAQ draft"],
    tool_surfaces: [
      { name: "Source asset", purpose: "Seed the repurposing run with a good proof point." },
      { name: "CMS or doc", purpose: "Draft and publish assets." },
      { name: "Distribution calendar", purpose: "Sequence where each asset goes." },
    ],
    steps: [
      { owner: "marketing", title: "Break the asset apart", description: "Separate the core proof point, the objection it answers, and the CTA it should support." },
      { owner: "gtm", title: "Keep the positioning tight", description: "Edit the repurposed assets so every one reinforces the same wedge." },
      { owner: "sales", title: "Deploy in the field", description: "Use the strongest outputs in outbound, follow-up, and objection handling." },
    ],
    implementation: {
      validated: "Repurpose one asset at a time in a shared document.",
      agentic: "Let Marketing draft variants while GTM trims them and Sales field-tests the proof snippets.",
      automation: "Later, route approved assets into CMS, scheduling, and sales enablement systems.",
    },
    metrics: ["Assets published per week", "Proof reuse rate", "Influence on replies or conversions"],
    tags: ["launch", "content", "proof"],
    fit: { distributions: ["Community-led", "Content-led", "Partnerships"] },
  },
  {
    slug: "weekly-demand-signal-brief",
    title: "Weekly demand signal brief",
    one_liner: "Roll research, customer notes, and competitor changes into one operating memo for the founder.",
    category: "GTM",
    stage: "Foundation",
    primary_agent: "gtm",
    support_agents: ["marketing", "sales"],
    setup_time: "1 hour weekly",
    automation_level: "Agent-assisted",
    objective: "Keep the founder oriented to what changed in the market instead of rerunning the whole opportunity thesis from scratch every week.",
    when_to_use: "Use this when multiple conversations, research sources, or experiments are happening and the team needs one weekly source of truth.",
    inputs: ["Source citations", "Call notes", "Pipeline changes", "Experiment results"],
    outputs: ["Weekly memo", "What changed", "What to stop", "What to test next"],
    tool_surfaces: [
      { name: "Opportunity sources", purpose: "Track the evidence base behind the claim." },
      { name: "CRM or notes", purpose: "Pull live buyer and pipeline data." },
      { name: "Shared memo", purpose: "Publish one weekly decision document." },
    ],
    steps: [
      { owner: "gtm", title: "Summarize the week", description: "Pull together the signals that changed the startup's risk or opportunity profile." },
      { owner: "sales", title: "Add market friction", description: "Contribute objection patterns and buyer urgency from live calls." },
      { owner: "marketing", title: "Reflect narrative changes", description: "Update message, proof, or content priorities based on the signals." },
    ],
    implementation: {
      validated: "Write it by hand in under one hour every Friday.",
      agentic: "Use GTM to draft the memo, then have Sales and Marketing append their sections before founder review.",
      automation: "Later, auto-collect source and CRM deltas into a draft memo.",
    },
    metrics: ["Founder decisions driven by the memo", "Time spent preparing weekly review", "Experiments retired vs. continued"],
    tags: ["signals", "operating-cadence", "founder"],
    fit: {},
  },
  {
    slug: "competitor-change-monitor",
    title: "Competitor change monitor",
    one_liner: "Watch how adjacent players reposition, price, and ship so your wedge stays differentiated.",
    category: "Marketing",
    stage: "Revenue",
    primary_agent: "marketing",
    support_agents: ["gtm"],
    setup_time: "1 hour weekly",
    automation_level: "Automate later",
    objective: "Track whether the category is getting crowded, shifting language, or validating the founder's wedge indirectly.",
    when_to_use: "Use this when the team needs a fast read on positioning drift or why prospects keep comparing the product to something else.",
    inputs: ["Competitor URLs", "Pricing pages", "Launch pages", "Sales call comparisons"],
    outputs: ["Change log", "Messaging differences", "Pricing deltas", "Response recommendations"],
    tool_surfaces: [
      { name: "Competitor pages", purpose: "Track actual shifts in copy, pricing, and product claims." },
      { name: "Call notes", purpose: "See which names buyers mention and why." },
      { name: "Notion or spreadsheet", purpose: "Keep an auditable log of changes over time." },
    ],
    steps: [
      { owner: "marketing", title: "Capture changes", description: "Log visible pricing, positioning, and feature shifts on the most relevant competitors." },
      { owner: "gtm", title: "Interpret the meaning", description: "Decide whether each shift is noise, validation, or a direct threat to the wedge." },
      { owner: "marketing", title: "Update outward-facing copy", description: "Adjust homepage, launch, or proof assets when the category language moves." },
    ],
    implementation: {
      validated: "Track changes manually in one weekly pass.",
      agentic: "Let Marketing summarize changes while GTM judges whether the founder should react.",
      automation: "Later, scrape or diff monitored pages and append deltas into the log automatically.",
    },
    metrics: ["Time from competitor change to response", "Number of copy updates driven by category drift"],
    tags: ["competition", "positioning", "category"],
    fit: {},
  },
  {
    slug: "product-demo-to-build-brief",
    title: "Product demo to build brief",
    one_liner: "Turn founder demos, call notes, and objections into the next engineering sprint without losing context.",
    category: "Engineering",
    stage: "Foundation",
    primary_agent: "engineering",
    support_agents: ["sales", "gtm"],
    setup_time: "Half day",
    automation_level: "Agent-assisted",
    objective: "Stop product feedback from dying in meeting notes and convert it into a scoped build sequence that supports the revenue motion.",
    when_to_use: "Use this once demos or pilots are happening and feature requests start piling up faster than the founder can prioritize them.",
    inputs: ["Build brief", "Demo notes", "Pilot requests", "Current backlog"],
    outputs: ["Scoped sprint brief", "Problem-to-feature mapping", "Do-not-build list", "Instrumentation needs"],
    tool_surfaces: [
      { name: "Build brief markdown", purpose: "Preserve the original product thesis." },
      { name: "Call or demo notes", purpose: "Bring the market signal into scope decisions." },
      { name: "Issue tracker", purpose: "Turn the selected changes into shipping work." },
    ],
    steps: [
      { owner: "sales", title: "Surface revenue pressure", description: "Tag the asks that are blocking deals, pilots, or activation." },
      { owner: "gtm", title: "Judge strategic fit", description: "Separate wedge-strengthening requests from distracting edge cases." },
      { owner: "engineering", title: "Scope the sprint", description: "Write the smallest implementation plan that moves the core workflow forward." },
    ],
    implementation: {
      validated: "Review recent demos and backlogs in one shared planning doc.",
      agentic: "Use the Engineering agent to propose scope after Sales and GTM annotate the asks.",
      automation: "Later, auto-pull tagged notes and backlog items into the next sprint brief.",
    },
    metrics: ["Time from request to scoped decision", "Revenue-linked requests shipped", "Requests deliberately deferred"],
    tags: ["product", "backlog", "founder-handoff"],
    fit: {},
  },
  {
    slug: "onboarding-friction-triage",
    title: "Onboarding friction triage",
    one_liner: "Find where users stall in the first workflow and route fixes back to the team fast.",
    category: "Engineering",
    stage: "Retention",
    primary_agent: "engineering",
    support_agents: ["marketing", "sales"],
    setup_time: "1 day",
    automation_level: "Agent-assisted",
    objective: "Protect early activation by identifying where the first promised value breaks down after sign-up or pilot start.",
    when_to_use: "Use this as soon as real users are touching the product and there is enough behavior or support signal to review.",
    inputs: ["Activation funnel events", "Support or onboarding notes", "User session summaries"],
    outputs: ["Friction board", "Top activation blockers", "Fix recommendations", "User-facing copy changes"],
    tool_surfaces: [
      { name: "Analytics", purpose: "Show where activation stalls." },
      { name: "Support notes", purpose: "Capture confusion and setup failures." },
      { name: "Issue tracker", purpose: "Route the most important fixes into shipping work." },
    ],
    steps: [
      { owner: "engineering", title: "Map the first-run path", description: "Identify the small set of actions that should lead to first value and instrument them." },
      { owner: "marketing", title: "Audit guidance", description: "Update copy, onboarding messages, and examples where users are confused." },
      { owner: "sales", title: "Close the loop", description: "Bring pilot feedback or deal-risk warnings into the same triage board." },
    ],
    implementation: {
      validated: "Run a weekly review of analytics and notes for the first-run experience.",
      agentic: "Engineering drafts the blocker list, Marketing rewrites copy, and Sales flags customers at risk.",
      automation: "Later, push anomaly alerts or support clusters into the triage queue automatically.",
    },
    metrics: ["Time to first value", "Activation rate", "Drop-off by onboarding step", "Support tickets per new account"],
    tags: ["activation", "retention", "product"],
    fit: {},
  },
  {
    slug: "integration-priority-board",
    title: "Integration priority board",
    one_liner: "Decide which integrations deserve to exist now versus which ones can stay manual or mocked.",
    category: "Engineering",
    stage: "Revenue",
    primary_agent: "engineering",
    support_agents: ["sales", "gtm"],
    setup_time: "2 hours",
    automation_level: "Manual-first",
    objective: "Prevent integration sprawl by tying each requested connector or data source to revenue, activation, or proof-of-value.",
    when_to_use: "Use this when prospects or early users keep asking for connectors, imports, or vendor-specific workflows.",
    inputs: ["Prospect requests", "Current product scope", "Manual workaround list"],
    outputs: ["Integration queue", "Revenue impact score", "Manual workaround policy", "Next build call"],
    tool_surfaces: [
      { name: "Pipeline notes", purpose: "See which deals are blocked by missing integrations." },
      { name: "Build brief", purpose: "Guard the original wedge and system boundaries." },
      { name: "Planning board", purpose: "Score what gets built, delayed, or faked manually." },
    ],
    steps: [
      { owner: "sales", title: "Gather demand", description: "List every requested integration and the deal or user context behind it." },
      { owner: "gtm", title: "Score strategic fit", description: "Judge whether the request strengthens the wedge or just chases account-specific edge cases." },
      { owner: "engineering", title: "Choose the path", description: "Decide whether to build, mock, import manually, or say no." },
    ],
    implementation: {
      validated: "Maintain one scored board in a shared planning doc.",
      agentic: "Engineering drafts the queue while GTM and Sales annotate urgency and strategic fit.",
      automation: "Later, sync integration requests from CRM and support into the same board automatically.",
    },
    metrics: ["Integration requests accepted vs. deferred", "Revenue unblocked per connector built", "Manual workaround frequency"],
    tags: ["integrations", "scope", "b2b"],
    fit: { audiences: ["B2B"] },
  },
  {
    slug: "case-study-extraction-engine",
    title: "Case study extraction engine",
    one_liner: "Turn live customer wins into proof assets that Sales and Marketing can immediately reuse.",
    category: "Sales",
    stage: "Revenue",
    primary_agent: "sales",
    support_agents: ["marketing"],
    setup_time: "2 hours",
    automation_level: "Agent-assisted",
    objective: "Make customer proof travel faster than the founder's memory so every win compounds into future revenue.",
    when_to_use: "Use this as soon as pilots, users, or service outcomes exist and the team needs sharper proof in the market.",
    inputs: ["Customer call notes", "Outcome metrics", "Screenshots or quotes", "Permission status"],
    outputs: ["Case study outline", "Proof snippets", "Objection-specific evidence", "Launch-ready customer story"],
    tool_surfaces: [
      { name: "Call notes", purpose: "Capture the customer's before, after, and buying trigger." },
      { name: "Outcome metrics", purpose: "Quantify the result where possible." },
      { name: "CMS or enablement doc", purpose: "Publish the story where the team can reuse it." },
    ],
    steps: [
      { owner: "sales", title: "Collect the evidence", description: "Pull the outcome, the setup pain, and the reasons the customer said yes." },
      { owner: "marketing", title: "Shape the story", description: "Turn the raw material into reusable proof assets by objection, channel, and buyer type." },
      { owner: "sales", title: "Deploy the proof", description: "Insert the strongest snippets into live deals and follow-up sequences." },
    ],
    implementation: {
      validated: "Write one proof story from each meaningful customer win.",
      agentic: "Sales drafts the raw notes and Marketing converts them into reusable collateral.",
      automation: "Later, trigger the workflow from a closed-won stage or success milestone.",
    },
    metrics: ["Proof assets created", "Sales reuse rate", "Influence on reply or close rates"],
    tags: ["proof", "revenue", "case-studies"],
    fit: {},
  },
];

function fitScore(values: string[] | undefined, target: string): number {
  if (!values?.length) return 1;
  return values.includes(target) ? 4 : 0;
}

export function scoreWorkflowFit(workflow: WorkflowTemplate, claim: ClaimedIdea | null): number {
  if (!claim) return 0;
  return [
    fitScore(workflow.fit.audiences, claim.audience),
    fitScore(workflow.fit.models, claim.model_type),
    fitScore(workflow.fit.industries, claim.industry),
    fitScore(workflow.fit.distributions, claim.distribution_play),
    fitScore(workflow.fit.founder_paths, claim.founder_path),
  ].reduce((sum, score) => sum + score, 0);
}

export function recommendedWorkflowsForClaim(claim: ClaimedIdea | null, limit = 6): WorkflowTemplate[] {
  return [...WORKFLOW_LIBRARY]
    .sort((a, b) => scoreWorkflowFit(b, claim) - scoreWorkflowFit(a, claim) || a.title.localeCompare(b.title))
    .slice(0, limit);
}

export function workflowFitNarrative(workflow: WorkflowTemplate, claim: ClaimedIdea | null): string | null {
  if (!claim) return null;
  const bits = [
    `${claim.audience} motion`,
    `${claim.distribution_play.toLowerCase()} distribution`,
    `${claim.time_to_launch.toLowerCase()} launch horizon`,
  ];
  return `${workflow.title} is recommended for ${claim.title} because it fits a ${bits.join(", ")} and keeps the team focused on one measurable execution loop.`;
}

export function workflowBySlug(slug: string) {
  return WORKFLOW_LIBRARY.find((workflow) => workflow.slug === slug) ?? null;
}
